#!/bin/bash
set -e

ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
#COL_MAGENTA=$ESC_SEQ"35;01m"
#COL_CYAN=$ESC_SEQ"36;01m"

## Functions we use
# Error

function error_exit {
        echo -en "$COL_RED$1$COL_RESET" 1>&2
        exit 1
}


# Show the butler function
display_logo() {
cat << "EOF"
          .--.
         /    \
        ## a  a
        (   '._)                Mr. Henry
         |'-- |                 ---------
       _.\___/_   ________
     ."\> \Y/|<'.  '._.-'       How do you do.
    /  \ \_\/ /  '-' /          May I introduce myself? I'm Henry.
    | --'\_/|/ |   _/           Glad to be your helping hand.
    |___.-' |  |`'`
      |     |  |                Please let me know how I can help !
      |    / './
     /__./` | |
        \   | |
         \  | |
         ;  | |
         /  | |
        |___\_.\_
        `-"--'---
EOF
}


# Display the logo
display_logo
